# .travis.yml
dist: precise

language: php

php:
  - 7.2

addons:
  mariadb: 10.4

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - cd src
  - pwd
  - mysql -u root -e 'CREATE DATABASE isa;'
  - mysql -u root -e "CREATE USER 'root'@'localhost' IDENTIFIED BY 'root';"
  - mysql -u root -e "GRANT ALL ON isa.* TO 'root'@'localhost';"
  - composer self-update
  - composer install 
  - php artisan migrate --force
  - cp .env.example .env
  - php artisan key:generate

script:
  - vendor/bin/phpunit

env:
    - APP_NAME="Laravel JWT Boilerplate"
    - APP_ENV=production
    - APP_KEY=base64:/HhrmYcqI8CQNMxjah/0ueNlKisxpaa5vriN49I02aU=
    - APP_DEBUG=true


    
    - DB_CONNECTION=mysql
    - DB_HOST=127.0.0.1
    - DB_PORT=3306
    - DB_DATABASE=isa
    - DB_USERNAME=user
    - DB_PASSWORD=user